
== E-Trace  Packets
(((Event Trace, E-Trace packets)))
(((E-Trace)))

For Event Trace, E-trace encoders will generate packets closely related to the format 1 and 3 instruction trace packets.

Each E-trace packet contains at most one address.  For the event types listed in <<tab:callret-events>> that requrie two addresses to be output, two E-trace packets will be generated.

Format 3 sync-event or sync-trap packets will be generated whenever a full address is required, otherwise format 1 packets will be used.

Although the packets are classified as format 3 and format 1, their payloads are not identical to their instruction trace equivalents, as event trace packets need to provide different information.  The decoder can determine whether to decode using the instruction trace or event trace formats from the format 3 subformat 3 (support) packet which will be ouptut before the first traced instruction is reported.

[[sec:format3]]
=== Format 3 packets

Format 3 packets are used for synchronization, traps, reporting context
and supporting information. There are 4 sub-formats.

[[sec:format33]]
=== Format 3 subformat 3 - Support

The structure of this packet is identical to the instruction trace sync-support packet as defined by the Standard Support Extension to E-trace.  However, the *encoder_mode* field will be set to 1 to indicate Event Trace.

[[sec:format30]]
=== Format 3 subformat 0 - Event

This packet format is used whenever a full address is required, and the event being reported is not a trap.  This includes privilege changes resulting from trap returns, as well as precise and asynchronous discontinuity context changes (see RHTI *ctype* signal).

The 2 reserved bits between *cause* and *address* keeps the address aligned at the same position in the packet as in the sync-trap packet.  This eliminates any additional muxing cost that would otherwise arise by having to place the address at a different offset in this packet compared to sync-trap or sync-start packets.

.Packet format 3, subformat 1
[align="center",float="center",cols="<12%,<20%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 11 (sync): synchronisation
|*subformat*| 2| 00 (event): Start of tracing, resync, or any time a full address is required
|reserved| 1| reserved
|*privilege*| _privilege_width_p_| The privilege level of the reported
instruction.
|*time*| _time_width_p_, or +
         0 if _notime_p_ is 1| The time value.
|*context*| _context_width_p_, or +
            0 if _nocontext_p_ is 1| The
instruction context
|*notify*| 1| Indicates if the packet was generated by a trace-notify trigger when 1.
|*cause*| 4| If *notify* = 1, it supplies the trigger ID. If *notify* = 0, this field indicates the reason for generating the packet: +
0000 CALL_SRCTGT (src *address*, call *itype* = 8) +
0001 CALL_SRCTGT or CALL_SRC (src *address*, call *itype* = 9) +
0010 CALL_TGT (tgt *address*, call *itype* = 8) +
0011 CALL_TGT (tgt *address*, call *itype* = 9) +
0100 RET_SRCTGT or RET_SRC (src *address*) +
0101 RET_TGT (tgt *address*) +
1000 EXIT_RESET +
1001 EXIT_DEBUG +
1010 EXIT_SECURITY +
1011 EXIT_UNBOUND +
1100 TRACE_ON_TRIGGER +
1101 TRACE_ON_FILTERED +
(other codes reserved)
|reserved| _ecause_width_p_ - 2| reserved
|*address*| _iaddress_width_p - iaddress_lsb_p_| Full instruction
address. Address alignment is determined by _iaddress_lsb_p_: *address*
must be left shifted by_iaddress-lsb_p_ in order to recreate original byte address.
|===

This packet type is used for *CALL_SRCTGT*, *CALL_SRC*, *CALL_TGT*, *RET_SRCTGT*, *RET_SRC*, *RET_TGT* or *trace-notify* event types when the first (or only) address must be reported in full (F-ADDR).


[[sec:format30]]
=== Format 3 subformat 1 - Trap

This packet structure is identical to the instruction trace sync-trap packet, except that the *branch* bit has no purpose and can be considered redefined as 'reserved'.

For Event Trace, the *thaddr* field will always be set to 1 for exceptions and 0 for interrupts.


[[sec:format32]]
=== Format 3 subformat 2 - Context

This packet is identical to the instruction trace sync-context packet, and is used to report imprecise context changes.

This file (E-Trace-packets.adoc) defines the E-Trace cite:[riscv-E-Trace-spec-2.0] packets for Event Trace.

[[sec:format1]]
=== Format 1 packets

This packet has sub-types with and without an address.

The with-address sub-type is always used for second address of the *CALL_SRCTGT* and *RET_SRCTGT* event types and for the first (or only) address of *CALL_SRCTGT*, *CALL_SRC*, *CALL_TGT*, *RET_SRCTGT*, *RET_SRC*, *RET_TGT* and *trace-notify* when it can be reported as a relative address (R-ADDR).

Reporting the address is optional for event types defined in <<tab:nonfunc-events>>, and these are supported by both sub-types.

Structurally it is arranged so that the *address* field starts at the same bit position as in the instruction trace format 1 packet reporting 1 branch.

.Packet format 1 - cause, address
[align="center",float="center",cols="<13%,<24%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 01 (diff-delta): includes event information and  differential address
|*addr_inc*| 1| Always 1 in this format
|*cause*| 4| If *notify* = 1, it supplies the trigger ID. If *notify* = 0, this field indicates the reason for generating the packet: +
0000 CALL_SRCTGT (*address* = src, call *itype* = 8) +
0001 CALL_SRCTGT or CALL_SRC (src *address*, call *itype* = 9) +
0010 CALL_SRCTGT or CALL_TGT (tgt *address*, call *itype* = 8) +
0011 CALL_SRCTGT or CALL_TGT (tgt *address*, call *itype* = 9) +
0100 RET_SRCTGT or RET_SRC (src *address*) +
0101 RET_SRCTGT or RET_TGT (src *address*) +
1000 ENTER_RESET +
1001 ENTER_DEBUG +
1010 ENTER_SECURITY +
1011 ENTER_UNBOUND +
1100 TRACE_OFF_TRIGGER +
1101 TRACE_OFF_FILTERED +
(other codes reserved)
|*notify*| 1| Indicates if the packet was generated by a trace-notify trigger when 1.
|*address*| _iaddress_width_p - iaddress_lsb_p_| Differential
instruction address.
|===

.Packet format 1 - cause only
[align="center",float="center",cols="<13%,<24%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 01 (diff-delta): includes event information
|*addr_inc*| 1| Always 0 in this format
|*cause*| 4| Indicates the reason for generating the packet: +
0000 EXIT_RESET +
0001 EXIT_DEBUG +
0010 EXIT_SECURITY +
0011 EXIT_UNBOUND +
0100 TRACE_ON_TRIGGER +
0101 TRACE_ON_FILTERED +
0110 RET +
1000 ENTER_RESET +
1001 ENTER_DEBUG +
1010 ENTER_SECURITY +
1011 ENTER_UNBOUND +
1100 TRACE_OFF_TRIGGER +
1101 TRACE_OFF_FILTERED +
(other codes reserved)
|===

[[sec:format2]]
=== Format 2 packets
This packet format is used for PC sampling.

Structurally it is identical to the instruction trace format 2 packet, but with all the bits above the address removed.

.Packet format 2
[align="center",float="center",cols="<11%,<24%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 10 (addr-only): differential address only
|*address*| _iaddress_width_p - iaddress_lsb_p_| Differential
instruction address.

|===
[[sec:format0]]
=== Format 0 packets
Plan to define for Performance counters.
