
== E-Trace  Packets
(((Event Trace, E-Trace packets)))
(((E-Trace)))

For Event Trace, E-trace encoders will generate packets closely related to the format 1 and 3 instruction trace packets.

Format 3 sync-event or sync-trap packets will be generated whenever a full address is required, otherwise format 1 packets will be used.

Although the packets are classified as format 3 and format 1, their payloads are not identical to their instruction trace equivalents, as event trace packets need to provide different information.  The decoder can determine whether to decode using the insturction trace or event trace formats from the format 3 subformat 3 (support) packet which will be ouptut before the first traced instruction is reported.

[[sec:format3]]
=== Format 3 packets

Format 3 packets are used for synchronization, traps, reporting context
and supporting information. There are 4 sub-formats.

[[sec:format33]]
=== Format 3 subformat 3 - Support

The structure of this packet is identical to the instruction trace sync-support packet as defined by the Standard Support Extension to E-trace.  However, the *encoder_mode* field will be set to 1 to indicate Event Trace.

[[sec:format30]]
=== Format 3 subformat 0 - Event

This packet format is used whenever a full address is required, and the event being reported is not a trap.  This includes privilege changes resulting from trap returns, as well as precise and asynchronous discontinuity context changes (see RHTI *ctype* signal).

The 2 reserved bits between *cause* and *address* keeps the address aligned at the same position in the packet as in the sync-trap packet.  This eliminates any additional muxing cost that would otherwise arise by having to place the address at a different offset in this packet compared to sync-trap or sync-start packets.

.Packet format 3, subformat 1
[align="center",float="center",cols="<12%,<20%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 11 (sync): synchronisation
|*subformat*| 2| 00 (event): Start of tracing, resync, or any time a full address is required
|*notify*| 1| Indicates if the packet was generated by a trace-notify trigger when 1.
|*privilege*| _privilege_width_p_| The privilege level of the reported
instruction.
|*time*| _time_width_p_, or +
         0 if _notime_p_ is 1| The time value.
|*context*| _context_width_p_, or +
            0 if _nocontext_p_ is 1| The
instruction context
|*cause*| 4| If *notify* = 0, this field suppies the _itype_ of the instruction.  If *notify* = 1, it supplies the trigger ID.
|reserved| _ecause_width_p_ - 2| reserved
|*address*| _iaddress_width_p - iaddress_lsb_p_| Full instruction
address. Address alignment is determined by _iaddress_lsb_p_: *address*
must be left shifted by_iaddress-lsb_p_ in order to recreate original byte address.
|===

[[sec:format30]]
=== Format 3 subformat 1 - Trap

This packet is identical to the instruction trace sync-trap packet, except that the *branch* bit has no purpose and can be considered redefined as 'reserved'.

[[sec:format32]]
=== Format 3 subformat 2 - Context

This packet is identical to the instruction trace sync-context packet, and is used to report imprecise context changes.

This file (E-Trace-packets.adoc) defines the E-Trace cite:[riscv-E-Trace-spec-2.0] packets for Event Trace.

[[sec:format1]]
=== Format 1 packets

This packet format is used for function calls and returns and notify triggers, whenever the address can be reported differentially.

Structurally it is arranged so that the *address* field starts at the same bit position as in the instruction trace format 1 packet reporting 1 branch.

The address is omitted for implicit returns.

.Packet format 1 - cause, address
[align="center",float="center",cols="<13%,<24%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 01 (diff-delta): includes event information and  differential address
|*cause*| 4| If *notify* = 0, this field suppies the _itype_ of the instruction.  If *notify* = 1, it supplies the trigger ID.
|*iret*| 1| Always 0 in this format
|*src*| 1| When set to 1 indicates that *cause* is the itype of the call/return and *address* is the address of the target. *cause* field
|*address*| _iaddress_width_p - iaddress_lsb_p_| Differential
instruction address.
|*notify*| 1| If the value of this bit is different from the MSB of
*address*, it indicates that this packet is reporting an instruction because of a trace-trigger.
|*updiscon*| 1| If the value of this bit is different from the MSB of
*notify*, it indicates that this packet is reporting the instruction
following an uninferable discontinuity and is also the instruction
before an exception, privilege change or resync (i.e. it will be
followed immediately by a format 3 _te_inst_).
|===

.Packet format 1 - cause only
[align="center",float="center",cols="<13%,<24%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 01 (diff-delta): includes event information and  differential address
|*cause*| 4| Supplies the _itype_ of the return instruction.
|*iret*| 1| Always 1 in this format
|===

==== Format 1 *src* field

Call/return instructions and their respective targets are usually reported as separate consecutive packets.  These packets will usually contain the *itype* corresponding *address*.  However, if for some reason the call/return instruction is not reported (e.g. due to filtering) then the packet reporting the target will include the *itype* of the call/return along with the *address* of the target.  This is indicated by the *src* field being 1.

[[sec:format2]]
=== Format 2 packets
This packet format is used for PC sampling.

Structurally it is identical to the instruction trace format 2 packet, but with all the bits above the address removed.

.Packet format 2
[align="center",float="center",cols="<11%,<24%,<~",options="header"]
|===
| *Field name*| *Bits*| *Description*
|*format*| 2| 10 (addr-only): differential address only
|*address*| _iaddress_width_p - iaddress_lsb_p_| Differential
instruction address.

|===
[[sec:format0]]
=== Format 0 packets
Plan to define for Performance counters.
