// 9-15-26 3am 
== Event Types and Message Contents

NOTE: Tracing uses address compression to reduce the number of bits used to mark executed addresses.  A non-compressed address is referred to as a Full Address, or *F-ADDR*. A Relative Address, or *R-ADDR* is a reduced-width address and as the name implies, is relative to and calculated from previous Full Addresses.

NOTE: One purpose of a Sync is to re-establish a Full Address of an executed instruction in the trace stream in order for the decoder to properly determine the location of the next executed instruction. In most cases it also requires tracing the current Privilege level, and in some cases, tracing the current Context ID for the decoder to determine the process or task that is executing.

Note: Context and Context ID are used interchangeably in this document.

Definition: *CauseID*: traced value identifying the cause of a Trace-on (Sync) or Trace-off event. The Trace Decoder uses it to label the cause of the message. This document uses symbolinc names for ID values; actual assigned values can be different between E-Trace and N-Trace. 

RHTI signals referenced in this spec: +
* trcstate[] +
* trigger[] +
* cause[] +
* priv[] +
* context[] +
* iaddr[] +
* iretire[]

NOTE: For exceptions and interrupts (itype=1 and 2 respectively), Event Trace deems it important to capture the xepc return address value. This was implemented in a pre-existing Event Trace implementation. +
The method: `xepc = iaddr + iretire`, when itype=1 or 2 +
where `iretire` is the "number of halfwords represented by instructions retired in this block". +
Note that there are exception cases where no instruction is retired, where iretire=0.

*NR* - Not Required

.List of Rules
[cols="50%", options="header"]
|===
^|Rules
a|* When an event trace packet that contains an instruction address is emitted, that address must be output in F-ADDR format if it is the first packet containing an address emitted after:
- enabling trace
- previously indicating trace has ended
- trcstate transitions to zero (debug exit, security filter exit, unbounded Wait exit)
- the resync timer has expired

a|* If a PC is filtered out or blocked by security, +
- the PC can either be omitted from a trace packet or the address set to 0 in a packet that includes the address. The trace decoder is responsible for interpreting address 0 as "unknown" or "excluded".

|===


NOTE: *resync timer* A periodic count is defined by *trTeInstSyncMax* and the value of trTeInstSyncMode value counts by packets, clock cycles, or instructions before a synchronization F-ADDR PC message is required. +
When the count-down condition is reached, hardware asserts a *sync_needed* flag (defined in this specification).  The next packet output requires the PC be an F-ADDR then *sync_needed* flag is reset.




.Event Types (non-function) and Message Contents
[cols="15%,35%,~", options="header"]
|===
^|Event ^|Cause ^| Outputs

.6+|Trace-on (Sync)
|* Exit from Reset
| CauseID=EXIT_RESET +
 PC of first instruction (NR) +
 PRIVILEGE mode, +
Context ID (NR)

|* Exit from Debug Mode +
(trcstate transition from 01 to 00)
| CauseID=EXIT_DEBUG +
 PC of first instruction after leaving debug (NR) +
 PRIVILEGE mode, +
Context ID (NR)

|* Exit from Security Filter +
(trcstate transition from 10 to 00)
| CauseID=EXIT_SECURITY +
 PC of first retired instruction after leaving Security Filter (NR) +
 PRIVILEGE mode, +
Context ID (NR)

|* Exit from Unbounded Wait +
(trcstate transition from 11 to 00)
| CauseID=EXIT_UNBOUNDED_WAIT +
 PC of first retired instruction after leaving Unbounded Wait (NR) +
 PRIVILEGE mode, +
Context ID (NR)

|Address, PRIV, or Context ID unfiltered
| CauseID=TRACE_ON_UNFILTERED +
 PC of first retired instruction after filtered-to-unfiltered  transition (NR) +
 PRIVILEGE mode, +
Context ID (NR)

|trace-on from trigger[] signal, SW writes to trTeControl bits, other
| CauseID=TRACE_ON_TRIGGER +
 PC of first retired instruction after trace-on transition (NR) +
 PRIVILEGE mode, +
Context ID (NR)

.6+|Trace-off
|* Enter Reset
| CauseID=ENTER_RESET +
PC = last instruction to execute before reset (NR) 

|* Enter Debug Mode +
(trcstate=01)
| CauseID=ENTER_DEBUG +
PC = address loaded into depc (but has not executed) (NR)

|* Entry into Security Filter +
(trcstate=10)
| CauseID=ENTER_SECURITY +
PC = last retired instruction before entering Security Filter (NR)

|* Unbounded Wait +
(trcstate=11)
| CauseID=ENTER_UNBOUNDED_WAIT +
PC = address of instruction such as WFI or WRS.NTO (NR)

|* Address, PRIV, or Context ID Filtered
| CauseID=TRACE_OFF_FILTERED +
 PC = last retired instruction before unfiltered-to-filtered transition (NR)

|* trace-off from trigger[] signal, SW writes to trTeControl bits, other
| CauseID=TRACE_OFF_TRIGGER +
 PC of last retired instruction before trace-off transition (NR)

|Exception
|Synchronous Faults, Traps, System Calls
|PC is the address of the instruction that incurred the exception, i.e. xepc which equals iaddr[]+iretire[] (NR) +
cause[] is what is loaded into the Exception Code field of xcause +
PRIVILEGE mode; optimally, only when PRIV value has changed

|Interrupt
|Asynchronous
|PC is the address of the last retired instruction before the interrupt was taken (iaddr[]) (NR) +
 (Returning from trap will resume execution at the next instruction after this PC, unless modified by OS). +
cause[] is what is loaded into the Exception Code field of xcause +
PRIVILEGE mode; optimally only when PRIV value has changed

|Return from trap
|Return from exception or interrupt (MRET or SRET executed)
|PCdest (R-ADDR) is address of instruction to begin execution after trap +
PRIVILEGE mode +
Context ID (NR)

|===

////
values assigned to CauseID
0 - EXIT_SECURITY
1 - ENTER_SECURITY
2 - EXIT_UNBOUND_WAIT
3 - ENTER_UNBOUND_WAIT
4 - EXIT_DEBUG
5 - ENTER_DEBUG
6 - EXIT_RESET
7 - ENTER_RESET
8 - TRACE_OFF_FILTERED
9 - TRACE_ON_UNFILTERED
10 - TRACE_ON_TRIGGER
11 - TRACE_OFF_TRIGGER
////

NOTE: Regarding the Event Trace decoder, for an Exception or Interrupt, if the user wants to view the instruction that caused the Exception, or the instruction that was interrupted from, the decoder will have to take the PC value recorded from the Exception or Interrupt, disassemble that instruction and from it, determine the next instruction executed.  For sequential instructions, the next instruction is the one after the Exception or Interrupt PC.  For an inferrable jump, the address of the next instruction is determined from the opcode.  For a conditional branch or uninferrable call, jump or return, the next instruction is not determinable. +
 +
If, however, the Return from Trap event is enabled, the decoder can use the PCdest value to determine the next instruction executed after the Exception or Interrupt, regardless of the opcode type.



=== Control bits for enabling Trace-on and Trace-off events

Each of the Trace-on (Sync) and Trace-off events in the table above can be enabled or disabled at run-time with control bits. There are separate bits for Trace-on and Trace-off transitions, and two GROUPs of type categories, for a total of 4 control bits. The groups are: +
GROUP1: Reset, Debug, Security Filter, and Unbounded Wait, the last three of which are trcstate[1:0] transitions, and +
GROUP2: Address, Privilege, or Context ID filtered/unfiltered, and Trace-on/off triggers.

Bits: +

* 0: GROUP1_ENTER (Trace-off) +
* 1: GROUP1_EXIT (Trace-on) +
* 2: GROUP2_ENTER (Trace-off) +
* 3: GROUP2_EXIT (Trace-on)


Read-only implementation bits will be defined for GROUP1 and 2 in the *trTeEvtFeatures* (later in this document) and the 4 Enable bits in the *trTeEvtControl* register. 