[[intro]]
== Introduction

Event Trace is an extension to the RISC-V Instruction Trace that provides hardware support for selectively tracing key executed events, called Event Types. It enables the capture of detailed execution information, which can be used for debugging, performance analysis, and system monitoring.

The Event Trace extension introduces new registers for setting up what trace events to trace, filters, and other controls.  Event Trace extends the existing Instruction Trace and leverages its trace formatting and use of trace sink options.

The key features of Event Trace are:

* timestamp each event to provide precise timing information for an execution timeline and for performance analysis.

* filter events based on type, privilege level, operation system context, and user-instrumented commands to reduce the volume of trace data and focus on relevant information.

* support for multiple event types which can be included or not included,
allowing control of the granularity of information traced.

* utilize many of the capabilities and features of the existing RISC-V Instruction Trace thus ensuring compatibility to the existing Instruction Trace to reduce development costs and limit the hardware size of Event Trace extensions.
