//[[RHTI Extensions]]
== RHTI Extensions for Event Trace
(((Event Trace, RHTI extensions)))

This file (RHTI-Extensions.adoc) defines extensions to the "RISC-V Hart to Trace Interface Specification"   cite:[riscv-RHTI-spec-0.83] to support several features for Event Trace.  While an implementer can wire up these signals "on their own", RHTI defines them, along with all the existing signal definitions for Instruction Trace, to provide the named signals for Event Trace use.

//[[Trigger/Watchpoint-ID, Trigger/Watchpoint ID]]
=== Trigger/Watchpoint ID
(((RHTI Extensions, Trigger/Watchpoint ID)))

As explained in the RHTI cite:[riscv-RHTI-spec-0.83] section of the specification, the debug module of the RISC-V hart may have a "Trigger Unit", also named "Trigger Module" in the RISC-V Debug specification cite:[riscv-debug-spec-1.0]. A 4-bit action field defines what happens when a trigger/watchpoint match occurs. Encoded codes 2-5 are for trace use.  The value 4 is *Trace-notify*.

The RHTI defines trigger +[2]+ signal to be *Trace-notify*.  When asserted, it indicates a match on one of the programmed hw triggers.

The following signal definition extends the section "Optional sideband signals",  Table 8 of the spec with the definition of *triggerID* which identifies *which* trigger matched.

.Optional sideband encoder *triggerID* output signals
[cols="12%, 20%,~",options="header"]
|===
^|*Signal* ^|*Group* ^|*Function*
|*triggerID* 
| OR +
("Optional Replicated" which means replicated N time for a hart that can retire N instructions per cycle with a trigger match on any of those instructions)
| 4-bit field that encodes the ID of the matching trigger, thus supports up to 16 triggers. +
There are two cases for multiple triggers matching on the same cycle: +
1) multiple triggers with the same match condition, which could include address-range triggers that overlap. (Also there is nothing to prevent a user from programming multiple triggers with the same match condition), or +
2) multiple triggers that occur when multiple instructions retire in the same cycle. +

The Event Trace debug trigger/watchpoint event is limited to one trigger match per cycle. In the case of multiple matches, for Case 1, the RHTI hardware must use numeric precedence to transmit (over this TriggerID field) the lowest ID value.  For Case 2, each of the potential matches on each of the retired instructions has its own, internal, 4-bit field. Logic in the core ORes the occurrence bits and also uses precedence to select the lowest numbered triggerID to transmit over the RHTI signal field.  
|===

//[[Performance Counter Selector Output]]
=== HPMeventX Output
(((RHTI Extensions, HPMeventX Output)))

.Optional sideband event selector outputs *HPMEventX* for Event Trace Encoder
[cols="35%, 10%, ~"]
|===
^|*Signal* ^|*Group* ^|*Function*
|*mhpmeventXOutput*[_eventNum_p-1_:0]
| O | Field that carries (routes) the least significant "Num" Hardware Performance Monitor (HPM) mhpmEventX selector outputs, where Num is _eventNum_p_. These signal outputs may be used for profiling performance counter delta counting or Selector-based event generation or both.

If HPM mhpmeventX selectors are being used (Alternative 2), _eventNum_p_ can range from 1 to 8.
|===

[#Instruction Retired Count]
=== Instruction Retired Count
(((RHTI Extensions, Instruction Retired Count)))

.Optional sideband encoder *InstRetCount* output signals
[cols="35%, 10%, ~"]
|===
^|*Signal* ^|*Group* ^|*Function*
|*instretcount*[_countwidth_p-1_:0]
| O | Number of instructions retired in this cycle. This is usable by trace to accumulate the total number of instructions retired at the time of a trace message. The width of this field is _countwidth_p_ which can be as small as 1 and as large as the encoded max number of retired instructions in any one cycle.

For example, if a core can retire up to 4 instructions per cycle, then a 3-bit width is required to encode the count of retired instructions from 0 to 4.

|===
